spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sinan}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 3000ms
sinan:
  server:
    base-url: ${SINAN_BASE_URL:https://sinan.host}
  upload:
    # 上传文件的基础路径
    base-path: ${UPLOAD_BASE_PATH:./upload}
    # 图标上传路径
    icon-path: ${UPLOAD_ICON_PATH:icons}
    # 访问URL前缀
    url-prefix: ${UPLOAD_URL_PREFIX:/api/bookmark}
favicon:
  cache:
    # favicon缓存目录
    dir: ${FAVICON_CACHE_DIR:upload/icons}
passkey:
  id: ${PASSKEY_ID:https://sinan.host}
  name: ${PASSKEY_NAME:sinan}
  origins:
    - ${PASSKEY_ORIGIN:https://sinan.host}
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: ASSIGN_UUID

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 7776000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

logging:
  level:
    pres.peixinyi.sinan: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
